### PR TITLE
make the garden.max_containers property configurable

### PR DESCRIPTION
**Pull request by joshzarrabi**
This will allow teams to more fully take advantage of underutilized workers. Often teams provision more workers than they actually need in order to create more room for containers. Instead they could just bump the max_containers and not have to get another worker.

Josh and @aemengo

Co-authored-by: Anthony Emengo <aemengo@pivotal.io>
Signed-off-by: Anthony Emengo <aemengo@pivotal.io>

### CODE REVIEW

**Comment by deniseyu** [comment]
hi @joshzarrabi @aemengo thanks for raising this!

We're hesitant about merging this because Garden's official guidance is that no more than 250 containers should be scheduled on a worker: https://bosh.io/jobs/garden?source=github.com/cloudfoundry/garden-linux-release&version=0.335.0#p%3dgarden.max_containers

@cirocosta has also done some investigation on performance degradation connected to increasing the number of cgroups running on a machine: https://github.com/concourse/hush-house/issues/22#issuecomment-500040191

**Comment by joshzarrabi** [comment]
Hi @deniseyu. I believe @aemengo talked to the garden team and they thought that warning might be out of date. I didn't know about @cirocosta's research though so maybe its not a great idea to do this.

**Comment by aemengo** [comment]
For context, this was conversation that transpired:

https://cloudfoundry.slack.com/archives/C033RE5D6/p1552656459345700

**Comment by deniseyu** [comment]
thanks @aemengo @joshzarrabi! i'm gonna copy+paste Julz' response here, for folks not on CF slack, for reference in case this causes any issues later hah, hopefully Julz won't mind:

> aemengo 6:27 AM
What happens if I increase garden.max_containers to ~1000 (on a highly performant VM)? Why is bumping it so advised against?
> julz 6:28 AM
nothing much @aemengo
the historical reasons for the limit are (a) the number of network IPs in the default subnet range (but you can increase that) (b) the max number of loop devices in the kernel is 255 and with garden-shed we used one loop for each container, but we no longer support garden-shed (c) we’ve never optimised or tested for much higher than 250 because it hasn’t been a big use case for us
so (a) and (b) are no longer a thing, (c) is still true, and there’s definitely a couple things we’d optimise differently if we heard lots of people were bumping that number (e.g. we have 3 or so goroutines and OS threads tied to each container which we’d probably want to change to use non-blocking IO), but it’s not what I’d call a massive issue tbh

how bout this compromise: we merge this in, but do you mind adding a caveat to the Description that this hasn't been tested above 250?

**Pull request merged**
